# Generated by Django 2.0.5 on 2018-05-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('detalleId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Nueva', 'NUEVA'), ('Activa', 'ACTIVA'), ('Finalizada', 'FINALIZADA'), ('Cancelada', 'CANCELADA')], help_text='Estado de la orden actual', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('ordenId', models.AutoField(primary_key=True, serialize=False)),
                ('nombreOrden', models.CharField(default='Orden de Compra', max_length=16)),
                ('horaRecepcion', models.TimeField(verbose_name='Hora_Recepcion')),
                ('horaEntregaAproximada', models.TimeField(verbose_name='Entrega_Aproximada')),
                ('horaEntrega', models.TimeField(verbose_name='Entrega')),
                ('facturaAsociada', models.CharField(blank=True, max_length=240, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada_en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='cliente.Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Estado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicioId', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=230, verbose_name='Servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('orden', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Orden')),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='detalle',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Orden'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='tipoServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Servicio'),
        ),
    ]
