# Generated by Django 2.0.4 on 2018-04-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0004_mascota_cliente'),
        ('cliente', '0008_auto_20180421_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('detalleId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('N', 'NUEVA'), ('A', 'ACTIVA'), ('F', 'FINALIZADA'), ('C', 'CANCELADA')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('ordenId', models.AutoField(primary_key=True, serialize=False)),
                ('horaRecepcion', models.TimeField(verbose_name='Hora_Recepcion')),
                ('horaEntregaAproximada', models.TimeField(verbose_name='Entrega_Aproximada')),
                ('horaEntrega', models.TimeField(verbose_name='Entrega')),
                ('facturaAsociada', models.CharField(max_length=240)),
                ('observaciones', models.TextField(max_length=500, verbose_name='Observaciones')),
                ('fechaCreacion', models.DateTimeField(verbose_name='Creada_en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Estado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicioId', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=230)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('tipoId', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipoServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Tipos'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='detalle',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Orden'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='tipoServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Servicio'),
        ),
    ]
