# Generated by Django 2.0.5 on 2018-06-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='cliente',
        ),
    ]
