# Generated by Django 2.0.5 on 2018-06-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='ordenDeTrabajo.Estado'),
        ),
    ]
