# Generated by Django 2.0.5 on 2018-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nombreOrden',
            field=models.CharField(default='Orden de Compra', max_length=16),
        ),
    ]
