# Generated by Django 2.0.5 on 2018-07-02 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='mascotas',
        ),
        migrations.AddField(
            model_name='orden',
            name='mascota',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='orden_mascota', to='mascota.Mascota'),
        ),
    ]
