# Generated by Django 2.0.5 on 2018-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada en'),
        ),
    ]
