# Generated by Django 2.0.5 on 2018-06-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='mascota',
        ),
    ]
