# Generated by Django 2.0.5 on 2018-07-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='mascota_servicio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_mascota', to='cliente.Cliente'),
        ),
    ]
