# Generated by Django 2.0.4 on 2018-04-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('Nueva', 'NUEVA'), ('Activa', 'ACTIVA'), ('Finalizada', 'FINALIZADA'), ('Cancelada', 'CANCELADA')], max_length=10),
        ),
    ]
