# Generated by Django 2.0.5 on 2018-05-20 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0002_auto_20180519_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='numeroOrden',
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='cliente.Cliente'),
        ),
    ]
