# Generated by Django 2.0.5 on 2018-07-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0002_auto_20180702_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='mascota',
        ),
    ]
