# Generated by Django 2.0.5 on 2018-06-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_remove_mascota_servicio_mascota'),
        ('ordenDeTrabajo', '0002_auto_20180621_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='mascota_servicio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_mascota', to='mascota.Mascota'),
        ),
    ]
