# Generated by Django 2.0.4 on 2018-04-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0002_auto_20180423_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='orden',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Orden'),
        ),
        migrations.AddField(
            model_name='tipos',
            name='orden',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ordenDeTrabajo.Orden'),
        ),
    ]
