# Generated by Django 2.0.4 on 2018-04-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0003_auto_20180423_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('Nueva', 'NUEVA'), ('Activa', 'ACTIVA'), ('Finalizada', 'FINALIZADA'), ('Cancelada', 'CANCELADA')], default='Nueva', help_text='Estado actual de la orden', max_length=10),
        ),
    ]
