# Generated by Django 2.0.5 on 2018-07-01 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
        ('ordenDeTrabajo', '0003_remove_servicio_mascota_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='mascota_servicio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_mascota', to='mascota.Mascota'),
        ),
    ]
