# Generated by Django 2.0.4 on 2018-04-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0004_auto_20180424_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('Nueva', 'NUEVA'), ('Activa', 'ACTIVA'), ('Finalizada', 'FINALIZADA'), ('Cancelada', 'CANCELADA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fechaCreacion',
            field=models.DateTimeField(verbose_name='Creada en'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='horaEntrega',
            field=models.TimeField(blank=True, verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='horaEntregaAproximada',
            field=models.TimeField(verbose_name='Entrega Aproximada'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='horaRecepcion',
            field=models.TimeField(verbose_name='Hora Recepcion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(max_length=230, verbose_name='Servicio'),
        ),
    ]
