# Generated by Django 2.0.4 on 2018-04-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0005_auto_20180426_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='tipoServicio',
        ),
    ]
