# Generated by Django 2.0.4 on 2018-04-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0006_remove_servicio_tiposervicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='facturaAsociada',
            field=models.CharField(max_length=240, verbose_name='Fact Asociada'),
        ),
    ]
