# Generated by Django 2.0.5 on 2018-05-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='zona',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cliente.Zona'),
        ),
    ]
