# Generated by Django 2.0.4 on 2018-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, verbose_name='publicado_en'),
        ),
    ]
