# Generated by Django 2.0.5 on 2018-05-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='publicado en'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
