# Generated by Django 2.0.4 on 2018-04-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20180415_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefono',
            old_name='tipodTelefono',
            new_name='tipodeTelefono',
        ),
    ]
