# Generated by Django 2.0.5 on 2018-05-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20180519_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, verbose_name='publicado en'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cliente.Cliente'),
        ),
    ]
