# Generated by Django 2.0.4 on 2018-04-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20180417_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='telefono',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
