# Generated by Django 2.0.5 on 2018-05-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20180530_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correo',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Correo',
        ),
    ]
