# Generated by Django 2.0.4 on 2018-04-17 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20180417_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='correo',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='Correo Invalido')]),
        ),
    ]
