# Generated by Django 2.0.5 on 2018-05-20 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20180520_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='cliente.Cliente'),
        ),
    ]
