# Generated by Django 2.0.4 on 2018-04-18 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20180417_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccionId', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=240)),
                ('colonia', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipioId', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zonaId', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='municipio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cliente.Municipio'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='zona',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='cliente.Zona'),
        ),
    ]
