# Generated by Django 2.0.4 on 2018-04-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20180418_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.TextField(max_length=240),
        ),
    ]
