# Generated by Django 2.0.4 on 2018-04-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20180419_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=240),
        ),
    ]
