# Generated by Django 2.0.4 on 2018-04-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('especieId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('tipoEspecie', models.CharField(choices=[('P', 'PERRO'), ('G', 'GATO'), ('O', 'OTRO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('mascotaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=240)),
                ('fechaNacimiento', models.DateField()),
                ('fechaCreacion', models.DateTimeField(verbose_name='publicado en')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('razaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('origen', models.CharField(max_length=128)),
            ],
        ),
    ]
