# Generated by Django 2.0.4 on 2018-04-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('especieId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('tipoEspecie', models.CharField(choices=[('Perro', 'PERRO'), ('Gato', 'GATO'), ('Otros', 'OTRO')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('kennelId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('mascotaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=240)),
                ('fechaNacimiento', models.DateField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='publicado en')),
                ('cliente', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('razaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('origen', models.CharField(max_length=130)),
                ('especie', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='mascota.Especie')),
                ('kennel', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='mascota.Kennel')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='mascota.Raza'),
        ),
        migrations.AddField(
            model_name='kennel',
            name='kennel',
            field=models.ManyToManyField(through='mascota.Raza', to='mascota.Especie'),
        ),
    ]
