# Generated by Django 2.0.5 on 2018-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre',
            new_name='nombreMascota',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='observaciones',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
