# Generated by Django 2.0.4 on 2018-04-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='mascota',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publicado en'),
        ),
    ]
