# Generated by Django 2.0.5 on 2018-05-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotaowner',
            name='owner',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
        migrations.DeleteModel(
            name='MascotaOwner',
        ),
    ]
