# Generated by Django 2.0.5 on 2018-06-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0002_auto_20180606_0354'),
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='serivio_mascota',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_mascota', to='ordenDeTrabajo.Servicio'),
        ),
    ]
