# Generated by Django 2.0.4 on 2018-04-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20180408_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('kennelId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='raza',
            name='mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='mascota.Raza'),
        ),
        migrations.AddField(
            model_name='raza',
            name='especie',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='mascota.Especie'),
        ),
        migrations.AddField(
            model_name='kennel',
            name='kennel',
            field=models.ManyToManyField(through='mascota.Raza', to='mascota.Especie'),
        ),
        migrations.AddField(
            model_name='raza',
            name='kennel',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='mascota.Kennel'),
        ),
    ]
