# Generated by Django 2.0.4 on 2018-04-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_auto_20180421_0502'),
        ('mascota', '0003_auto_20180408_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
