# Generated by Django 2.0.4 on 2018-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20180426_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='tipoEspecie',
            field=models.CharField(choices=[('Perro', 'P'), ('Gato', 'G'), ('Otros', 'O')], max_length=5),
        ),
    ]
