# Generated by Django 2.0.5 on 2018-05-20 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20180520_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='cliente.Cliente'),
        ),
    ]
