# Generated by Django 2.0.4 on 2018-04-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20180426_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='tipoEspecie',
            field=models.CharField(choices=[('Perro', 'PERRO'), ('Gato', 'GATO'), ('Otros', 'OTROS')], max_length=5),
        ),
    ]
