# Generated by Django 2.0.5 on 2018-05-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20180520_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='observaciones',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso'),
        ),
    ]
