# Generated by Django 2.0.5 on 2018-05-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_auto_20180520_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kennel',
            old_name='nombre',
            new_name='nombreKennel',
        ),
        migrations.RenameField(
            model_name='raza',
            old_name='nombre',
            new_name='nombreRaza',
        ),
        migrations.AddField(
            model_name='especie',
            name='nombreEspecie',
            field=models.CharField(default=True, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especie',
            name='tipoEspecie',
            field=models.CharField(max_length=5),
        ),
    ]
