# Generated by Django 2.0.5 on 2018-05-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0008_auto_20180520_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kennel',
            old_name='nombreKennel',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='raza',
            old_name='nombreRaza',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='nombreEspecie',
        ),
        migrations.AlterField(
            model_name='especie',
            name='tipoEspecie',
            field=models.CharField(choices=[('Perro', 'PERRO'), ('Gato', 'GATO'), ('Otros', 'OTRO')], max_length=5),
        ),
    ]
