# Generated by Django 2.0.5 on 2018-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0009_auto_20180520_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='observaciones',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
    ]
